version: "3.8"
services:
  db:
    image: postgres
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env/development/database
  web:
    build: .
    volumes:
      - .:/myapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    env_file:
      - .env/development/database
      - .env/development/host
    depends_on:
      - db
volumes:
  postgres:
